N = (input('Digite algo: '))
print('Qual o tipo primitivo?: ', type(N))
print('E um número?: ', N.isnumeric())
print('E alfanumérico?:', N.isalnum())
print('E alfabético?: ', N.isalpha())
print('Esta minúscula?: ', N.islower())
print('Esta maiúscula?: ', N.isupper())
print('Esta capitalizada/titulo?: ', N.istitle())
print('Só tem espaços?: ', N.isspace())
print('Decimal?: ', N.isdecimal())
